# Generated by Django 2.2.17 on 2021-03-26 13:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_account', models.CharField(max_length=32, unique=True, verbose_name='person_account')),
                ('period', models.DateField(verbose_name='period')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='payer')),
            ],
        ),
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_account', models.CharField(max_length=32, unique=True, verbose_name='person_account')),
                ('period', models.CharField(max_length=128, verbose_name='period')),
                ('name', models.CharField(max_length=128, verbose_name='services')),
                ('address', models.CharField(max_length=128, verbose_name='address')),
                ('square', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='square')),
                ('num_resident', models.PositiveIntegerField(default=0, verbose_name='num_resident')),
                ('uk', models.CharField(max_length=512, verbose_name='uk')),
            ],
        ),
    ]
