# Generated by Django 2.2.17 on 2021-03-29 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20210329_0654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='services')),
                ('unit', models.CharField(max_length=32, verbose_name='unit')),
                ('standart', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='standart')),
                ('rate', models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='rate')),
                ('factor', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='factor')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='services_activ')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='name_category')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='category_is_active')),
            ],
        ),
        migrations.DeleteModel(
            name='TypeServices',
        ),
        migrations.AddField(
            model_name='services',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.ServicesCategory'),
        ),
    ]
