# Generated by Django 2.2.17 on 2021-03-27 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20210326_2108'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payer',
        ),
        migrations.AddField(
            model_name='user',
            name='invoice',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='invoice.Invoice'),
        ),
    ]
