# Generated by Django 2.2.17 on 2021-03-27 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_auto_20210327_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='person_account',
        ),
    ]
