# Generated by Django 2.2.17 on 2021-03-27 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_auto_20210327_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='appartament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invoice.Appartament'),
        ),
    ]
