# Generated by Django 2.2.17 on 2021-03-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_auto_20210327_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personal_account',
            field=models.CharField(max_length=32, unique=True, verbose_name='personal_account'),
        ),
    ]
