# Generated by Django 2.2.17 on 2021-03-27 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_auto_20210327_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appartament',
            options={'default_related_name': 'appartament'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'default_related_name': 'city'},
        ),
        migrations.AlterModelOptions(
            name='house',
            options={'default_related_name': 'house'},
        ),
        migrations.AlterModelOptions(
            name='street',
            options={'default_related_name': 'street'},
        ),
        migrations.AlterModelOptions(
            name='typeservices',
            options={'default_related_name': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='uk',
            options={'default_related_name': 'uk'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'default_related_name': 'user'},
        ),
        migrations.AlterField(
            model_name='appartament',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appartament', to='invoice.House'),
        ),
        migrations.AlterField(
            model_name='house',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house', to='invoice.City'),
        ),
        migrations.AlterField(
            model_name='house',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house', to='invoice.Street'),
        ),
        migrations.AlterField(
            model_name='house',
            name='uk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house', to='invoice.UK'),
        ),
        migrations.AlterField(
            model_name='user',
            name='appartament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='invoice.Appartament'),
        ),
        migrations.AlterField(
            model_name='user',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='invoice.Invoice'),
        ),
    ]
